"""Initial migration

Revision ID: 308c7567898b
Revises: 59446477c0d8
Create Date: 2025-06-06 09:58:49.475742

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '308c7567898b'
down_revision = '59446477c0d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
