"""Initial migration with all tables

Revision ID: 59446477c0d8
Revises: 
Create Date: 2025-06-03 14:55:42.684400

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59446477c0d8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accommodation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accommodation', schema=None) as batch_op:
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###
